#!/bin/sh

### BEGIN INIT INFO
# Provides:        gateAlarm
# Required-Start:  $network $local_fs
# Required-Stop:   $network $local_fs
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start gateAlarm
### END INIT INFO

case "$1" in
  start)
    echo "Starting gateAlarm"
    python3 /usr/local/sbin/startGateAlarm.py &
    ;;
  stop)
    echo "Stopping gateAlarm"
    # kill application you want to stop
    kill $(ps aux | grep "python3 /usr/local/sbin/startGateAlarm.py" | grep -v grep | awk '{print $2}')
    ;;
  *)
    echo "Usage: /etc/init.d/gateAlarm {start|stop}"
    exit 1
    ;;
esac

exit 0

